### ISSUE TITLE
Add documentation files.

### ISSUE THREAD

**Issue by romavini** [GET-Prog/flappy#1]
Add files to better describe the repository, such as:
 - README.md
 - LICENSE
 - CONTRIBUTING
 - ...

Any extra files to add?
@brnomendes @dsambugaro @thiagohoh

**Comment by brnomendes** [comment]
[The Hitchhiker’s Guide to Python - Structuring Your Project](https://docs.python-guide.org/writing/structure/#sample-repository)
[Kenneth Reitz - Repository Structure and Python](https://kennethreitz.org/essays/2013/01/27/repository-structure-and-python)
[Better Programming - The Complete Guide to Creating Python Packages](https://betterprogramming.pub/the-complete-guide-to-creating-python-packages-3ecb150a1a43)
